### ISSUE TITLE
Example SPIRAM test app shows SRAM test failing

### ISSUE THREAD

**Issue by kevinttt** [feilipu/Goldilocks_Analogue_SPIRAM_Library#1]
Hi,
When running the example SPIRAM application on my KS Goldilocks Analogue board, I'm getting a failure for the SRAM test, but the EEPROM test seems to pass fine.  Example output from the serial port is as follows:

0 
SPI SRAM Memory Testing: 
Testing at 0x0 for 8096 bytes 
Testing... Error at 0x0 with 0x81 
***\* FAILED ***

SPI EEPROM Memory Testing: 
Testing at 0x1000000 for 8096 bytes 
Testing... PASSED

4 
SPI SRAM Memory Testing: 
Testing at 0x4 for 8096 bytes 
Testing... Error at 0x4 with 0x76 
***\* FAILED ***

SPI EEPROM Memory Testing: 
Testing at 0x1000004 for 8096 bytes 
Testing... PASSED

and so on up to 0x3FC then it starts again.  Apologies if I'm missing something obvious in the set-up somewhere!

Many Thanks,
Kevin

**Comment by feilipu** [comment]
Kevin,

this looks at first glance as if it is a hardware issue.
Given it is failing the factory test, I'm surprised that this is happening.

There are two things I can suggest to isolate it a bit further.

First, in the example code there are some lines commented out. Remove the comment slashes and include the code and upload it. I've reproduced the code to include below

```
    //    Testing visually check each (supposedly) written byte, and the return byte from SRAM / EEPROM.
    //    Serial.print(F("Written 0x"));
    //    Serial.print(Buff[i], HEX);
    //    Serial.print(F(" Read 0x"));
    //    Serial.println(read_result, HEX);
```

This will give us a view of what was supposed to be written, and what the program has received back from the chip. Then we can see whether it is a random return value, or something else enlightening.

Paste some of the result here in a new comment.

Then, upload the [TestSuite program](https://github.com/feilipu/Arduino_FreeRTOS_Library/tree/master/examples/GoldilocksAnalogueTestSuite) (don't forget the formatted uSD card), then using the smartphone headphones listen to hear whether you can hear the 8 second delay loop. What, if anything, can you hear?

Best regards, Phillip

**Comment by kevinttt** [comment]
Ok, I powered the thing up today, just as I left it yesterday to try a few things, including the ones you suggested above, but it is now fine!  It was failing the test suite - that was what first put me onto the issue.  But today, test works fine (including the audio test).  I've just re-downloaded the SPIRAM test and that too is now all fine, so that is a bit of a mystery.  I was going to try some known-answer tests to see if there was any pattern to the failure.

The only thing different was powering it up with a set of headphones/mic plugged in, but I've since re-powered on/off without it and it is still fine.  Yesterday was the first time I'd powered the thing up at all.

I guess now, I'll just try using it in anger and see how I go!  If it starts failing again, I'll see if I can narrow it down a bit ...

Thanks,
Kevin

**Comment by feilipu** [comment]
Kevin,

That's strange behaviour.

My first thought was that it is somehow related to the supply voltage, but the 23LC1024 SRAM is specified down to 2.5V. So that's not the cause.

Perhaps put the SRAM testing code into a small function that you can call each time the board starts up and use it in every sketch, just so that you can be confident that it is working every time.

Let me know if it reoccurs.

Best regards, Phillip
